# Generated by Django 2.0.5 on 2018-05-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0003_auto_20180530_1355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qcwytable',
            table=None,
        ),
    ]
