# Generated by Django 2.0.5 on 2018-05-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0002_auto_20180530_1349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qcwytable',
            table='qcwytable',
        ),
    ]
